#pragma once

#define NICKEL2_STAGE_PRE_ALPHA
#define NICKEL2_STAGE_ALPHA
#define NICKEL2_STAGE_BETA
#define NICKEL2_STAGE_RELEASE_CANDIDATE
#define NICKEL2_STAGE_RELEASE

#define NICKEL2_VERSION_MAJOR 2024
#define NICKEL2_VERSION_MINOR 1
#define NICKEL2_VERSION_REVISION 0
#define NICKEL2_VERSION_BUILD 43
#define NICKEL2_VERSION_BUILD_DATE "2024-03-03"
#define NICKEL2_VERSION_STAGE NICKEL2_STAGE_PRE_ALPHA
#define NICKEL2_VERSION_STRING "2024.1.43-pre.0"