#pragma once

#if !defined(NK_VERSION_STRING)
#define NK_STAGE_PRE_ALPHA 0
#define NK_STAGE_ALPHA 1
#define NK_STAGE_BETA 2
#define NK_STAGE_RELEASE_CANDIDATE 3
#define NK_STAGE_RELEASE 4

#define NK_VERSION_MAJOR 2024
#define NK_VERSION_MINOR 1
#define NK_VERSION_REVISION 0
#define NK_VERSION_BUILD 723
#define NK_VERSION_BUILD_DATE "2024-10-29"
#define NK_VERSION_STAGE NK_STAGE_PRE_ALPHA
#define NK_VERSION_STRING "2024.1.723-pre.0"
#endif