#pragma once

#include <GLFW/glfw3.h>

#define NICKEL2_MOUSE_BUTTON_1 GLFW_MOUSE_BUTTON_1
#define NICKEL2_MOUSE_BUTTON_2 GLFW_MOUSE_BUTTON_2
#define NICKEL2_MOUSE_BUTTON_3 GLFW_MOUSE_BUTTON_3
#define NICKEL2_MOUSE_BUTTON_4 GLFW_MOUSE_BUTTON_4
#define NICKEL2_MOUSE_BUTTON_5 GLFW_MOUSE_BUTTON_5
#define NICKEL2_MOUSE_BUTTON_6 GLFW_MOUSE_BUTTON_6
#define NICKEL2_MOUSE_BUTTON_7 GLFW_MOUSE_BUTTON_7
#define NICKEL2_MOUSE_BUTTON_8 GLFW_MOUSE_BUTTON_8
#define NICKEL2_MOUSE_BUTTON_LAST GLFW_MOUSE_BUTTON_LAST
#define NICKEL2_MOUSE_BUTTON_LEFT GLFW_MOUSE_BUTTON_LEFT
#define NICKEL2_MOUSE_BUTTON_RIGHT GLFW_MOUSE_BUTTON_RIGHT
#define NICKEL2_MOUSE_BUTTON_MIDDLE GLFW_MOUSE_BUTTON_MIDDLE

#define NICKEL2_KEY_SPACE GLFW_KEY_SPACE
#define NICKEL2_KEY_APOSTROPHE GLFW_KEY_APOSTROPHE
#define NICKEL2_KEY_COMMA GLFW_KEY_COMMA
#define NICKEL2_KEY_MINUS GLFW_KEY_MINUS
#define NICKEL2_KEY_PERIOD GLFW_KEY_PERIOD
#define NICKEL2_KEY_SLASH GLFW_KEY_SLASH
#define NICKEL2_KEY_0 GLFW_KEY_0
#define NICKEL2_KEY_1 GLFW_KEY_1
#define NICKEL2_KEY_2 GLFW_KEY_2
#define NICKEL2_KEY_3 GLFW_KEY_3
#define NICKEL2_KEY_4 GLFW_KEY_4
#define NICKEL2_KEY_5 GLFW_KEY_5
#define NICKEL2_KEY_6 GLFW_KEY_6
#define NICKEL2_KEY_7 GLFW_KEY_7
#define NICKEL2_KEY_8 GLFW_KEY_8
#define NICKEL2_KEY_9 GLFW_KEY_9
#define NICKEL2_KEY_SEMICOLON GLFW_KEY_SEMICOLON
#define NICKEL2_KEY_EQUAL GLFW_KEY_EQUAL
#define NICKEL2_KEY_A GLFW_KEY_A
#define NICKEL2_KEY_B GLFW_KEY_B
#define NICKEL2_KEY_C GLFW_KEY_C
#define NICKEL2_KEY_D GLFW_KEY_D
#define NICKEL2_KEY_E GLFW_KEY_E
#define NICKEL2_KEY_F GLFW_KEY_F
#define NICKEL2_KEY_G GLFW_KEY_G
#define NICKEL2_KEY_H GLFW_KEY_H
#define NICKEL2_KEY_I GLFW_KEY_I
#define NICKEL2_KEY_J GLFW_KEY_J
#define NICKEL2_KEY_K GLFW_KEY_K
#define NICKEL2_KEY_L GLFW_KEY_L
#define NICKEL2_KEY_M GLFW_KEY_M
#define NICKEL2_KEY_N GLFW_KEY_N
#define NICKEL2_KEY_O GLFW_KEY_O
#define NICKEL2_KEY_P GLFW_KEY_P
#define NICKEL2_KEY_Q GLFW_KEY_Q
#define NICKEL2_KEY_R GLFW_KEY_R
#define NICKEL2_KEY_S GLFW_KEY_S
#define NICKEL2_KEY_T GLFW_KEY_T
#define NICKEL2_KEY_U GLFW_KEY_U
#define NICKEL2_KEY_V GLFW_KEY_V
#define NICKEL2_KEY_W GLFW_KEY_W
#define NICKEL2_KEY_X GLFW_KEY_X
#define NICKEL2_KEY_Y GLFW_KEY_Y
#define NICKEL2_KEY_Z GLFW_KEY_Z
#define NICKEL2_KEY_LEFT_BRACKET GLFW_KEY_LEFT_BRACKET
#define NICKEL2_KEY_BACKSLASH GLFW_KEY_BACKSLASH
#define NICKEL2_KEY_RIGHT_BRACKET GLFW_KEY_RIGHT_BRACKET
#define NICKEL2_KEY_GRAVE_ACCENT GLFW_KEY_GRAVE_ACCENT
#define NICKEL2_KEY_WORLD_1 GLFW_KEY_WORLD_1
#define NICKEL2_KEY_WORLD_2 GLFW_KEY_WORLD_2
#define NICKEL2_KEY_ESCAPE GLFW_KEY_ESCAPE
#define NICKEL2_KEY_ENTER GLFW_KEY_ENTER
#define NICKEL2_KEY_TAB GLFW_KEY_TAB
#define NICKEL2_KEY_BACKSPACE GLFW_KEY_BACKSPACE
#define NICKEL2_KEY_INSERT GLFW_KEY_INSERT
#define NICKEL2_KEY_DELETE GLFW_KEY_DELETE
#define NICKEL2_KEY_RIGHT GLFW_KEY_RIGHT
#define NICKEL2_KEY_LEFT GLFW_KEY_LEFT
#define NICKEL2_KEY_DOWN GLFW_KEY_DOWN
#define NICKEL2_KEY_UP GLFW_KEY_UP
#define NICKEL2_KEY_PAGE_UP GLFW_KEY_PAGE_UP
#define NICKEL2_KEY_PAGE_DOWN GLFW_KEY_PAGE_DOWN
#define NICKEL2_KEY_HOME GLFW_KEY_HOME
#define NICKEL2_KEY_END GLFW_KEY_END
#define NICKEL2_KEY_CAPS_LOCK GLFW_KEY_CAPS_LOCK
#define NICKEL2_KEY_SCROLL_LOCK GLFW_KEY_SCROLL_LOCK
#define NICKEL2_KEY_NUM_LOCK GLFW_KEY_NUM_LOCK
#define NICKEL2_KEY_PRINT_SCREEN GLFW_KEY_PRINT_SCREEN
#define NICKEL2_KEY_PAUSE GLFW_KEY_PAUSE
#define NICKEL2_KEY_F1 GLFW_KEY_F1
#define NICKEL2_KEY_F2 GLFW_KEY_F2
#define NICKEL2_KEY_F3 GLFW_KEY_F3
#define NICKEL2_KEY_F4 GLFW_KEY_F4
#define NICKEL2_KEY_F5 GLFW_KEY_F5
#define NICKEL2_KEY_F6 GLFW_KEY_F6
#define NICKEL2_KEY_F7 GLFW_KEY_F7
#define NICKEL2_KEY_F8 GLFW_KEY_F8
#define NICKEL2_KEY_F9 GLFW_KEY_F9
#define NICKEL2_KEY_F10 GLFW_KEY_F10
#define NICKEL2_KEY_F11 GLFW_KEY_F11
#define NICKEL2_KEY_F12 GLFW_KEY_F12
#define NICKEL2_KEY_F13 GLFW_KEY_F13
#define NICKEL2_KEY_F14 GLFW_KEY_F14
#define NICKEL2_KEY_F15 GLFW_KEY_F15
#define NICKEL2_KEY_F16 GLFW_KEY_F16
#define NICKEL2_KEY_F17 GLFW_KEY_F17
#define NICKEL2_KEY_F18 GLFW_KEY_F18
#define NICKEL2_KEY_F19 GLFW_KEY_F19
#define NICKEL2_KEY_F20 GLFW_KEY_F20
#define NICKEL2_KEY_F21 GLFW_KEY_F21
#define NICKEL2_KEY_F22 GLFW_KEY_F22
#define NICKEL2_KEY_F23 GLFW_KEY_F23
#define NICKEL2_KEY_F24 GLFW_KEY_F24
#define NICKEL2_KEY_F25 GLFW_KEY_F25
#define NICKEL2_KEY_KP_0 GLFW_KEY_KP_0
#define NICKEL2_KEY_KP_1 GLFW_KEY_KP_1
#define NICKEL2_KEY_KP_2 GLFW_KEY_KP_2
#define NICKEL2_KEY_KP_3 GLFW_KEY_KP_3
#define NICKEL2_KEY_KP_4 GLFW_KEY_KP_4
#define NICKEL2_KEY_KP_5 GLFW_KEY_KP_5
#define NICKEL2_KEY_KP_6 GLFW_KEY_KP_6
#define NICKEL2_KEY_KP_7 GLFW_KEY_KP_7
#define NICKEL2_KEY_KP_8 GLFW_KEY_KP_8
#define NICKEL2_KEY_KP_9 GLFW_KEY_KP_9
#define NICKEL2_KEY_KP_DECIMAL GLFW_KEY_KP_DECIMAL
#define NICKEL2_KEY_KP_DIVIDE GLFW_KEY_KP_DIVIDE
#define NICKEL2_KEY_KP_MULTIPLY GLFW_KEY_KP_MULTIPLY
#define NICKEL2_KEY_KP_SUBTRACT GLFW_KEY_KP_SUBTRACT
#define NICKEL2_KEY_KP_ADD GLFW_KEY_KP_ADD
#define NICKEL2_KEY_KP_ENTER GLFW_KEY_KP_ENTER
#define NICKEL2_KEY_KP_EQUAL GLFW_KEY_KP_EQUAL
#define NICKEL2_KEY_LEFT_SHIFT GLFW_KEY_LEFT_SHIFT
#define NICKEL2_KEY_LEFT_CONTROL GLFW_KEY_LEFT_CONTROL
#define NICKEL2_KEY_LEFT_ALT GLFW_KEY_LEFT_ALT
#define NICKEL2_KEY_LEFT_SUPER GLFW_KEY_LEFT_SUPER
#define NICKEL2_KEY_RIGHT_SHIFT GLFW_KEY_RIGHT_SHIFT
#define NICKEL2_KEY_RIGHT_CONTROL GLFW_KEY_RIGHT_CONTROL
#define NICKEL2_KEY_RIGHT_ALT GLFW_KEY_RIGHT_ALT
#define NICKEL2_KEY_RIGHT_SUPER GLFW_KEY_RIGHT_SUPER
#define NICKEL2_KEY_MENU GLFW_KEY_MENU

namespace nickel2 {
    namespace input {
        extern double scrollX, scrollY;
        void scrollCallback(GLFWwindow* window, double xoffset, double yoffset);
    }

    class InputHandler {
        private:
            GLFWwindow* window;
            double& scrollX, scrollY;

        public:
            InputHandler(GLFWwindow* window);
            ~InputHandler();

            bool getKey(int32_t key);
            bool getMouseButton(int32_t button);
            void getCursorPosition(double* x, double* y);
            void setCursorPosition(double x, double y);
            void setCursorVisible(bool visible);
            void destroy();
    };
}